pull_request_rules:
  - name: default
    conditions:
      - label=ready-to-be-merged
      - label!=no-mergify
      - '#approved-reviews-by>=1'
      - status-success=WIP
      - status-success=continuous-integration/travis-ci/pr
      - status-success=coverage/coveralls
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true
