rules:
  default:
    protection:
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/travis-ci
          - coverage/coveralls
    merge_strategy:
      method: rebase
    enabling_label: ready-to-be-merged
